// WRITE A PROGRAM SHOWING THE DIFFERENCE BETWEEN /* */ AND // COMMENTS.

#include<stdio.h>
int main(){
    /*THIS IS USED TO WRITE A MULTI LINE COMMENTS.
    IT SPAN MULTIPLE LINES.
    IT CAN ALSO BE USED AS AN INLINE COMMENT ON A SINGLE LINE eg.. int x = /* default*/
    printf("HELLO JYOTI THAKUR");
    // THIS IS USED TO WRITE A SINGLE LINE COMMENT.AUTOMATICALLY COMMENT OUT EVERYTHING TO THE RIGHT OF IT UNTIL THE LINE ENDS.
    return 0;
}